### ISSUE TITLE
Type mismatch for Pulumi.AzureNextGen.Web.V20150801.ServerFarm.status

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/pulumi-azure-nextgen#118]
```
Diagnostics:
  pulumi:pulumi:Stack (example-dev):
    error: Running program 'C:\example\bin\Debug\netcoreapp3.1\example.dll' failed with an unhandled exception:
    System.InvalidOperationException: Expected System.String but got System.Double deserializing Pulumi.AzureNextGen.Web.V20150801.ServerFarm.status
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType, ImmutableHashSet`1 resources)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by mikhailshilkov** [comment]
Any specific reason why you are using this old API version? Does it happen with newer versions?

**Comment by jamesianberry** [comment]
Actually the code was from arm2pulumi when it still generated C#, and it selected the old API even though the ARM template specified `"apiVersion": "2018-11-01"`.

I tried newer APIs but got similar to `error CS0234: The type or namespace name 'ServerFarm' does not exist in the namespace 'Pulumi.AzureNextGen.Web.Latest' (are you missing an assembly reference?)` for all of them.

Now I am converting the code to use Latest by changing e.g. Web.ServerFarm to Web.AppServicePlan and making other required changes...

**Comment by mikhailshilkov** [comment]
@viveklak Should arm2pulumi go "up" in versions when e.g. "2018-11-01" is not found, not down to "V20150801"?

> `Microsoft.Web/sites/Pulumi.Input`1[System.String]`

This doesn't look healthy - type name shouldn't be there. If you can't fix it, feel free to show some code here.

**Comment by jamesianberry** [comment]
Thanks - here's the code:
```
using Pulumi;
using Pulumi.AzureNextGen.Resources.Latest;
using Web = Pulumi.AzureNextGen.Web.Latest;

class ExampleArgs
{
    public ResourceGroup ResourceGroup { get; set; } = null!;
    public Input<string> ExampleName { get; set; } = null!;
}

class Example : ComponentResource
{
    public Example(string name, ExampleArgs args, ComponentResourceOptions? options = null)
    : base("example:web:app", name, options)
    {
        var ExampleAppServicePlan = new Web.AppServicePlan("ExampleAppServicePlan", new Web.AppServicePlanArgs
        {
            Kind = "app",
            Location = args.ResourceGroup.Location,
            Name = args.ExampleName,
            PerSiteScaling = false,
            Reserved = false,
            ResourceGroupName = args.ResourceGroup.Name,
            Sku = new Web.Inputs.SkuDescriptionArgs
            {
                Capacity = 2,
                Family = "Pv2",
                Name = "P3v2",
                Size = "P3v2",
                Tier = "PremiumV2",
            },
        });

        var ExampleWebApp = new Web.WebApp("ExampleWebApp", new Web.WebAppArgs
        {
            ClientAffinityEnabled = false,
            ClientCertEnabled = false,
            ContainerSize = 0,
            Enabled = true,
            HostNameSslStates = 
            {
                new Web.Inputs.HostNameSslStateArgs
                {
                    Name = $"{args.ExampleName}.azurewebsites.net",
                    SslState = "Disabled",
                },
                new Web.Inputs.HostNameSslStateArgs
                {
                    Name = $"{args.ExampleName}.scm.azurewebsites.net",
                    SslState = "Disabled",
                },
            },
            HostNamesDisabled = false,
            Kind = "app",
            Location = args.ResourceGroup.Location,
            Name = args.ExampleName,
            ResourceGroupName = args.ResourceGroup.Name,
            ScmSiteAlsoStopped = false,
            ServerFarmId = ExampleAppServicePlan.Id,
            SiteConfig = {},
        });

        var ExampleWebAppHostNameBinding = new Web.WebAppHostNameBinding("ExampleWebAppHostNameBinding", new Web.WebAppHostNameBindingArgs
        {
            HostName = $"{args.ExampleName}/{args.ExampleName}.azurewebsites.net",
            HostNameType = "Verified",
//            Location = args.ResourceGroup.Location,
            Name = $"{args.ExampleName}/{args.ExampleName}.azurewebsites.net",
            ResourceGroupName = args.ResourceGroup.Name,
            SiteName = ExampleWebApp.Name,
        });

        var ExampleWebAppSlot = new Web.WebAppSlot("ExampleWebAppSlot", new Web.WebAppSlotArgs
        {
            ClientAffinityEnabled = true,
            ClientCertEnabled = false,
            ContainerSize = 0,
            Enabled = true,
            HostNameSslStates = 
            {
                new Web.Inputs.HostNameSslStateArgs
                {
                    Name = $"{args.ExampleName}-backstage.azurewebsites.net",
                    SslState = "Disabled",
                },
                new Web.Inputs.HostNameSslStateArgs
                {
                    Name = $"{args.ExampleName}-backstage.scm.azurewebsites.net",
                    SslState = "Disabled",
                },
            },
            HostNamesDisabled = false,
            Kind = "app",
            Location = args.ResourceGroup.Location,
            Name = $"{args.ExampleName}/backstage",
            ResourceGroupName = args.ResourceGroup.Name,
            ScmSiteAlsoStopped = false,
            ServerFarmId = ExampleAppServicePlan.Id,
            SiteConfig = {},
            Slot = $"{args.ExampleName}/backstage",
        });

        this.AppServicePlanId = ExampleAppServicePlan.Id;
        this.WebAppId = ExampleWebApp.Id;
        this.WebAppHostNameBindingId = ExampleWebAppHostNameBinding.Id;
        this.WebAppSlotId = ExampleWebAppSlot.Id;
    }

    [Output]
    public Output<string> AppServicePlanId { get; set; }
    [Output]
    public Output<string> WebAppId { get; set; }
    [Output]
    public Output<string> WebAppHostNameBindingId { get; set; }
    [Output]
    public Output<string> WebAppSlotId { get; set; }
}
```

**Comment by mikhailshilkov** [comment]
You can't do `$"{args.ExampleName}/backstage"`, it should be `Output.Format($"{args.ExampleName}/backstage")` instead (the same applies to other spots where you format outputs)

**Comment by jamesianberry** [comment]
So that made some progress:
```
Updating (example/dev)

View Live: https://app.pulumi.com/example/eg/dev/updates/36

     Type                                        Name                    Status                  Info
     pulumi:pulumi:Stack                         example-dev             **failed**              1 error
 +   ├─ meandu:app:example                       Example                 created
 +   ├─ azure-nextgen:web/latest:AppServicePlan  ExampleAppServicePlan   created
 +   ├─ azure-nextgen:web/latest:WebAppSlot      ExampleWebAppSlot       **creating failed**     1 error
 +   └─ azure-nextgen:web/latest:WebApp          ExampleWebApp           created

Diagnostics:
  azure-nextgen:web/latest:WebAppSlot (ExampleWebAppSlot):
    error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/example' under resource group 'example' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

  pulumi:pulumi:Stack (example-dev):
    error: update failed

Resources:
    + 3 created
    2 unchanged

Duration: 34s
```
I was thinking I need to sort out dependencies but:
```
Updating (example/dev)

View Live: https://app.pulumi.com/example/example/dev/updates/37

     Type                                               Name                           Status                  Info
     pulumi:pulumi:Stack                                example-dev                    **failed**              1 error
 +   ├─ azure-nextgen:web/latest:WebAppSlot             ExampleWebAppSlot              **creating failed**     1 error
 +   └─ azure-nextgen:web/latest:WebAppHostNameBinding  ExampleWebAppHostNameBinding   **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (example-dev):
    error: update failed
 
  azure-nextgen:web/latest:WebAppSlot (ExampleWebAppSlot):
    error: Code="Failed" Message="The async operation failed."

  azure-nextgen:web/latest:WebAppHostNameBinding (ExampleWebAppHostNameBinding):
    error: Code="Failed" Message="The async operation failed."

Resources:
    5 unchanged

Duration: 5s
```
So even though `args.ExampleName` is technically an Input we need the Output.Format?

**Comment by mikhailshilkov** [comment]
> So even though args.ExampleName is technically an Input we need the Output.Format?

`Input<T>` is a type that can be either `Output<T>` or `T`. But yes, because both are possible, `Output.Format` is needed. If you never pass an output as an input value, you can change the type to just `public string ExampleName` and then use this string freely.

As a rule of thumb, names in resource properties should not contain any slashes (as opposed to ARM templates, where names are sometimes composite). For App Service sub-resources, `Name` is the name of the app service itself. The following resource succeeds for me:

```cs
var ExampleWebAppSlot = new WebAppSlot("ExampleWebAppSlot", new WebAppSlotArgs
{
    ClientAffinityEnabled = true,
    ClientCertEnabled = false,
    ContainerSize = 0,
    Enabled = true,
    HostNamesDisabled = false,
    Kind = "app",
    Location = resourceGroup.Location,
    Name = ExampleWebApp.Name,
    ResourceGroupName = resourceGroup.Name,
    ScmSiteAlsoStopped = false,
    ServerFarmId = ExampleAppServicePlan.Id,
    Slot = "backstage",
});
```

Note the values for `Name` and `Slot`.

I don't have a custom domain to try the binding, but it should probably be

```cs
ar ExampleWebAppHostNameBinding = new WebAppHostNameBinding("ExampleWebAppHostNameBinding", new WebAppHostNameBindingArgs
{
    HostName = "www.example.com",
    HostNameType = "Verified",
    Name = ExampleWebApp.Name,
    ResourceGroupName = resourceGroup.Name,
    SiteName = ExampleWebApp.Name,
});
```

I'm not exactly sure what you are trying to achieve with `{args.ExampleName}/{args.ExampleName}.azurewebsites.net`. I suppose that the `azurewebsites.net` binding is created automatically and you only need to create custom ones?

**Comment by viveklak** [comment]
The nested name might have been generated by arm2pulumi. I filed https://github.com/pulumi/pulumi-azure-nextgen/issues/121 to track that.

**Comment by jamesianberry** [comment]
Can confirm only need binding for custom domains.
The nested name was generated by arm2pulumi.
Changed inputs-only to strings.
Component reliably builds, now checking against original ARM template - seems I need to adjust some parameters.
