### ISSUE TITLE
Pulumi.AzureNextGen.DocumentDB.Latest.SqlResourceSqlDatabase throws exception on decoding response

### ISSUE THREAD

**Issue by bantoni** [pulumi/pulumi-azure-nextgen#14]
Hey,

I'm playing around with version 0.1.0 of the Azure next gen provider and I'm facing an exception when creating a Cosmos DB database within my Cosmos DB account. Actually it creates the database, but when the provider tries to decode the response from Azure it fails due to a mismatch of data types. The provider tries to convert a double into an ImmutableDictionary<string, Object>:

```
error: Running program 'C:\***\bin\Debug\netcoreapp3.1\Infrastructure.dll' failed with an unhandled exception:
    System.InvalidOperationException: Expected System.Collections.Immutable.ImmutableDictionary`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] but got System.Double deserializing Pulumi.AzureNextGen.DocumentDB.Latest.Outputs.SqlDatabaseGetPropertiesResponseResource(ts)
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

Cheers,
Benedikt

**Comment by mikhailshilkov** [comment]
Thank you for reporting @bantoni, I'm taking a look!

**Comment by mikhailshilkov** [comment]
I tried the following code but it succeeded.

```cs
var sqlResourceSqlDatabase = new SqlResourceSqlDatabase("sqlResourceSqlDatabase", new SqlResourceSqlDatabaseArgs
        {
            AccountName = "myaccount",
            DatabaseName = "mydbcs",
            Location = "westeurope",
            Resource = new SqlDatabaseResourceArgs
            {
                Id = "mydbcs"
            },
            Options = new CreateUpdateOptionsArgs(),
            ResourceGroupName = "myrg"
        });
```

@bantoni Could you provide your program to repro the issue?

**Comment by mikhailshilkov** [comment]
Ah, now I got it reproduced.

**Comment by william-liebenberg** [comment]
Getting the same behavior - any idea for a temp workaround?

**Comment by mikhailshilkov** [comment]
This will be fixed in the next dev build (in a couple of hours) and the next stable release (in a few days)

**Comment by mikhailshilkov** [comment]
This NuGet version contains the fix: https://www.nuget.org/packages/Pulumi.AzureNextGen/0.1.1-alpha.1601196036
