### ISSUE TITLE
Difficulty enabling ContainerInsights for AKS

### ISSUE THREAD

**Issue by ellesde** [pulumi/pulumi-azure-nextgen#144]
I'm having difficult enabling ContainerInsights for AKS in Go. It seems like pulumi is trying to resolve the `omsagent`'s identity right away. This is causing a nil pointer dereference when doing `pulumi up`.

Relevant code below:
```golang
id, err := random.NewRandomUuid(ctx, "aks_oms", nil)
if err != nil {
	return err
}

_, err = authorization.NewRoleAssignment(ctx, "aks_oms", &authorization.RoleAssignmentArgs{
    Scope:              aks.ID(),
    RoleAssignmentName: id.Result,
    Properties: authorization.RoleAssignmentPropertiesArgs{
        RoleDefinitionId: pulumi.Sprintf("/subscriptions/%v/providers/Microsoft.Authorization/roleDefinitions/3913510d-42f4-4e42-8a64-420c390055eb", sub),
        PrincipalId:      aks.AddonProfiles.MapIndex(pulumi.String("omsagent")).Identity().ObjectId().Elem(),
    },
}, pulumi.DependsOn([]pulumi.Resource{aks}))
		
if err != nil {
    return err
}
```

And the error being returned:
```
panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb1f225]
    goroutine 210 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.StringPtrOutput.Elem.func1(0x0, 0x0, 0x0)
        /home/ellesde/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.14.0/go/pulumi/types_builtins.go:6623 +0x5
    reflect.Value.call(0x3255400, 0x3b04d48, 0x13, 0x3ac4bc0, 0x4, 0xc000420528, 0x1, 0x1, 0x10, 0x10, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8c7
    reflect.Value.Call(0x3255400, 0x3b04d48, 0x13, 0xc000420528, 0x1, 0x1, 0x32f1140, 0xc000424200, 0xc0000b3bd8)
        /usr/local/go/src/reflect/value.go:337 +0xb9
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.makeContextful.func1(0xc000420510, 0x2, 0x2, 0xc000420510, 0x3, 0x468633)
        /home/ellesde/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.14.0/go/pulumi/types.go:286 +0x7c
    reflect.callReflect(0xc000338570, 0xc0000b3bd8, 0xc0000b3bc0)
        /usr/local/go/src/reflect/value.go:565 +0x32a
    reflect.makeFuncStub(0x3bcba40, 0xc000128038, 0x0, 0x0, 0x0, 0x3208360, 0x0, 0xc0004204e0, 0xc0000b3e30, 0x4a42a7, ...)
        /usr/local/go/src/reflect/asm_amd64.s:20 +0x42
    reflect.Value.call(0xc000336300, 0xc000338570, 0x13, 0x3ac4bc0, 0x4, 0xc0000b3f60, 0x2, 0x2, 0x3356a00, 0x3208360, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8c7
    reflect.Value.Call(0xc000336300, 0xc000338570, 0x13, 0xc000367f60, 0x2, 0x2, 0xc0004241f0, 0x1, 0x1)
        /usr/local/go/src/reflect/value.go:337 +0xb9
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext.func1(0xc00033a9a0, 0x3bcba40, 0xc000128038, 0x3bec540, 0xc00033aa10, 0xc000336300, 0xc000338570, 0x13)
        /home/ellesde/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.14.0/go/pulumi/types.go:410 +0x28e
    created by github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext
        /home/ellesde/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.14.0/go/pulumi/types.go:398 +0x1ed
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by mikhailshilkov** [comment]
This is tracked in #115

For now, you would need to add a nil check inside your call chain to avoid the panic.

**Comment by ellesde** [comment]
Thank you! The following worked:

```golang
_, err = authorization.NewRoleAssignment(ctx, "aks_oms", &authorization.RoleAssignmentArgs{
    Scope:              aks.ID(),
    RoleAssignmentName: id.Result,
    PrincipalId: aks.AddonProfiles.MapIndex(pulumi.String("omsagent")).Identity().ObjectId().ApplyString(func(s *string) string {
	if s == nil {
		return "0"
	}

	return *s
    }),
    RoleDefinitionId: pulumi.Sprintf("/subscriptions/%v/providers/Microsoft.Authorization/roleDefinitions/3913510d-42f4-4e42-8a64-420c390055eb", sub),
})
```

**Comment by mikhailshilkov** [comment]
Great to know! I'll close this issue and let's track a better solution in #115
