### ISSUE TITLE
Out of memory during import

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#214]
Importing all or just a part of the resources below fails with cli an out of memory error. If I import one or two at a time it seems to work, but quite tedious. When I had the ImportId within the code for each resource and did a preview, I never encountered these out of memory exceptions. I run within a docker container in both cases, when it works and does not work.

```
{
"resources": [
    {
        "type": "azure-nextgen:resources/latest:ResourceGroup",
        "name": "rg-Test1922",
        "id": "$resourceIdPrefix"
    },
    {
        "type": "azure-nextgen:insights/latest:Component",
        "name": "ai-Test1922",
        "id": "$resourceIdPrefix/providers/microsoft.insights/components/Test1922-AppInsights"
    },
    {
        "type": "azure-nextgen:insights/latest:ComponentCurrentBillingFeature",
        "name": "ai-cbf-Test1922",
        "id": "$resourceIdPrefix/providers/microsoft.insights/components/Test1922-AppInsights/CurrentBillingFeatures"
    },
    {
        "type": "azure-nextgen:storage/latest:StorageAccount",
        "name": "sa-test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.Storage/storageAccounts/test1922"
    },
    {
        "type": "azure-nextgen:storage/latest:StorageAccount",
        "name": "sa-test1922storage",
        "id": "$resourceIdPrefix/providers/Microsoft.Storage/storageAccounts/test1922storage"
    },
    {
        "type": "azure-nextgen:storage/latest:BlobContainer",
        "name": "sasc-test1922storage-logs",
        "id": "$resourceIdPrefix/providers/Microsoft.Storage/storageAccounts/test1922storage/blobServices/default/containers/logs"
    },
    {
        "type": "azure-nextgen:eventhub/latest:Namespace",
        "name": "ehn-Test1922-EventHub",
        "id": "$resourceIdPrefix/providers/Microsoft.EventHub/namespaces/Test1922-EventHub"
    },
    {
        "type": "azure-nextgen:eventhub/latest:EventHub",
        "name": "eh-Test1922-EventHub-test1922-eventhub1",
        "id": "$resourceIdPrefix/providers/Microsoft.EventHub/namespaces/Test1922-EventHub/eventhubs/test1922-eventhub1"
    },
    {
        "type": "azure-nextgen:eventhub/latest:ConsumerGroup",
        "name": "ehcg-Test1922-EventHub-test1922-eventhub1-production",
        "id": "$resourceIdPrefix/providers/Microsoft.EventHub/namespaces/Test1922-EventHub/eventhubs/test1922-eventhub1/consumergroups/production"
    },
    {
        "type": "azure-nextgen:eventhub/latest:ConsumerGroup",
        "name": "ehcg-Test1922-EventHub-test1922-eventhub1-exp",
        "id": "$resourceIdPrefix/providers/Microsoft.EventHub/namespaces/Test1922-EventHub/eventhubs/test1922-eventhub1/consumergroups/exp"
    },
    {
        "type": "azure-nextgen:devices/v20200615:IotHubResource",
        "name": "ih-Test1922-IoTHub",
        "id": "$resourceIdPrefix/providers/Microsoft.Devices/IotHubs/Test1922-IoTHub"
    },
    {
        "type": "azure-nextgen:web/v20200601:AppServicePlan",
        "name": "asp-Test1922-Plan",
        "id": "$resourceIdPrefix/providers/Microsoft.Web/serverfarms/Test1922-Plan"
    },
    {
        "type": "azure-nextgen:web/v20200601:WebApp",
        "name": "wa-Test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.Web/sites/Test1922"
    },
    {
        "type": "azure-nextgen:web/v20200601:WebApp",
        "name": "was-Test1922-exp",
        "id": "$resourceIdPrefix/providers/Microsoft.Web/sites/Test1922/slots/exp"
    },
    {
        "type": "azure-nextgen:web/latest:WebAppDiagnosticLogsConfiguration",
        "name": "wadlc-Test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.Web/sites/Test1922/config/logs"
    },
    {
        "type": "azure-nextgen:web/latest:WebAppDiagnosticLogsConfiguration",
        "name": "wadlc-Test1922-exp",
        "id": "$resourceIdPrefix/providers/Microsoft.Web/sites/Test1922/slots/exp/config/logs"
    },
    {
        "type": "azure-nextgen:sql/latest:Server",
        "name": "ss-test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.Sql/servers/test1922"
    },
    {
        "type": "azure-nextgen:sql/latest:FirewallRule",
        "name": "ssfr-test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.Sql/servers/test1922/firewallRules/Connectitude"
    },
    {
        "type": "azure-nextgen:sql/latest:Database",
        "name": "sdb-test1922-test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.Sql/servers/test1922/databases/Test1922"
    },
    {
        "type": "azure-nextgen:containerregistry/latest:Registry",
        "name": "cr-Test1922",
        "id": "$resourceIdPrefix/providers/Microsoft.ContainerRegistry/registries/Test1922"
    }
]
}
```

```
fatal error: runtime: out of memory

runtime stack:

runtime.throw(0x126107a, 0x16)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/panic.go:1116 +0x72

runtime.sysMap(0xc00c000000, 0x4000000, 0x212ebb8)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mem_linux.go:169 +0xc6

runtime.(*mheap).sysAlloc(0x2112da0, 0x400000, 0x7fffffffffff, 0x14f3150)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/malloc.go:727 +0x1e5

runtime.(*mheap).grow(0x2112da0, 0x1, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mheap.go:1344 +0x85

runtime.(*mheap).allocSpan(0x2112da0, 0x1, 0x7f0f8a3e0700, 0x212ebc8, 0x7f0f898bee70)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mheap.go:1160 +0x6b6

runtime.(*mheap).alloc.func1()

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mheap.go:907 +0x65

runtime.systemstack(0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/asm_amd64.s:370 +0x66

runtime.mstart()

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/proc.go:1116

goroutine 1 [running]:

runtime.systemstack_switch()

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/asm_amd64.s:330 fp=0xc000106448 sp=0xc000106440 pc=0x468a80

runtime.(*mheap).alloc(0x2112da0, 0x1, 0x450107, 0x10de100)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mheap.go:901 +0x85 fp=0xc000106498 sp=0xc000106448 pc=0x427825

runtime.(*mcentral).grow(0x2123958, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mcentral.go:506 +0x7a fp=0xc0001064e0 sp=0xc000106498 pc=0x418a1a

runtime.(*mcentral).cacheSpan(0x2123958, 0x7f0f898baed8)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mcentral.go:177 +0x3e5 fp=0xc000106558 sp=0xc0001064e0 pc=0x4187a5

runtime.(*mcache).refill(0x7f0fb1053108, 0x107)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/mcache.go:142 +0xa5 fp=0xc000106578 sp=0xc000106558 pc=0x418145

runtime.(*mcache).nextFree(0x7f0fb1053108, 0x7, 0x108bc60, 0x48d301, 0xc00bffe180)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/malloc.go:880 +0x8d fp=0xc0001065b0 sp=0xc000106578 pc=0x40d26d

runtime.mallocgc(0x20, 0x0, 0x0, 0xc0041645e1)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/malloc.go:1061 +0x834 fp=0xc000106650 sp=0xc0001065b0 pc=0x40dc54

runtime.slicebytetostring(0x0, 0xc00bffe180, 0x14, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/string.go:110 +0x90 fp=0xc000106680 sp=0xc000106650 pc=0x450990

encoding/json.(*decodeState).literalStore(0xc0005c4028, 0xc0041645e0, 0x1b, 0x563820, 0x108ba20, 0xc00a31d4e0, 0x198, 0x1a9c500, 0x1ac44d3, 0xc0005c4050)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:955 +0x1ed7 fp=0xc000106818 sp=0xc000106680 pc=0x75e457

encoding/json.(*decodeState).value(0xc0005c4028, 0x108ba20, 0xc00a31d4e0, 0x198, 0x108ba20, 0xc00a31d4e0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:384 +0x1f1 fp=0xc000106880 sp=0xc000106818 pc=0x758b71

encoding/json.(*decodeState).object(0xc0005c4028, 0x10547a0, 0xc00bff9528, 0x196, 0xc0005c4050, 0x7b)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:765 +0x12fe fp=0xc000106b10 sp=0xc000106880 pc=0x75b3de

encoding/json.(*decodeState).value(0xc0005c4028, 0x10547a0, 0xc00bff9528, 0x196, 0x10547a0, 0xc00bff9528)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:370 +0x6d fp=0xc000106b78 sp=0xc000106b10 pc=0x7589ed

encoding/json.(*decodeState).object(0xc0005c4028, 0x11b26c0, 0xc00bff9500, 0x199, 0x1254af1, 0xb)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:765 +0x12fe fp=0xc000106e08 sp=0xc000106b78 pc=0x75b3de

encoding/json.(*decodeState).value(0xc0005c4028, 0x11b26c0, 0xc00bff9500, 0x199, 0x11b26c0, 0xc00bff9500)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:370 +0x6d fp=0xc000106e70 sp=0xc000106e08 pc=0x7589ed

encoding/json.(*decodeState).array(0xc0005c4028, 0x10739c0, 0xc0000793b8, 0x197, 0xc0005c4050, 0x5b)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:558 +0x1aa fp=0xc000106f58 sp=0xc000106e70 pc=0x7595ca

encoding/json.(*decodeState).value(0xc0005c4028, 0x10739c0, 0xc0000793b8, 0x197, 0x10739c0, 0xc0000793b8)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:360 +0x105 fp=0xc000106fc0 sp=0xc000106f58 pc=0x758a85

encoding/json.(*decodeState).object(0xc0005c4028, 0x11b25e0, 0xc000079380, 0x199, 0xc0005c4050, 0x7b)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:765 +0x12fe fp=0xc000107250 sp=0xc000106fc0 pc=0x75b3de

encoding/json.(*decodeState).value(0xc0005c4028, 0x11b25e0, 0xc000079380, 0x199, 0xc00bfdbf20, 0x99)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:370 +0x6d fp=0xc0001072b8 sp=0xc000107250 pc=0x7589ed

encoding/json.(*decodeState).object(0xc0005c4028, 0x10e00e0, 0xc00007c170, 0x195, 0xc0005c4050, 0x7b)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:765 +0x12fe fp=0xc000107548 sp=0xc0001072b8 pc=0x75b3de

encoding/json.(*decodeState).value(0xc0005c4028, 0x10e00e0, 0xc00007c170, 0x195, 0x10e00e0, 0xc00007c170)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:370 +0x6d fp=0xc0001075b0 sp=0xc000107548 pc=0x7589ed

encoding/json.(*decodeState).object(0xc0005c4028, 0x1054720, 0xc00007c160, 0x16, 0xc0005c4050, 0x7b)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:765 +0x12fe fp=0xc000107840 sp=0xc0001075b0 pc=0x75b3de

encoding/json.(*decodeState).value(0xc0005c4028, 0x1054720, 0xc00007c160, 0x16, 0xc00068b920, 0x76db99)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:370 +0x6d fp=0xc0001078a8 sp=0xc000107840 pc=0x7589ed

encoding/json.(*decodeState).unmarshal(0xc0005c4028, 0x1054720, 0xc00007c160, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/decode.go:180 +0x1ea fp=0xc000107930 sp=0xc0001078a8 pc=0x75816a

encoding/json.(*Decoder).Decode(0xc0005c4000, 0x1054720, 0xc00007c160, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/encoding/json/stream.go:73 +0x16b fp=0xc000107970 sp=0xc000107930 pc=0x76d82b

github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.LoadMetadata(0x1adff20, 0x17df7f, 0x17df7f, 0x0, 0x0, 0x13ea940)

        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:107 +0x10e fp=0xc0001079c0 sp=0xc000107970 pc=0xfd382e

github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.makeProvider(0xc0004e35a0, 0x125675c, 0xd, 0x13cab04, 0x6, 0x1c5dea0, 0x47e8fe, 0x47e8fe, 0x1adff20, 0x17df7f, ...)

        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:65 +0x113 fp=0xc000107c08 sp=0xc0001079c0 pc=0xfd3173

github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.Serve.func1(0xc0004e35a0, 0xc0005863c0, 0xc000586390, 0xc000607d90, 0xc0005ba000)

        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/serve.go:15 +0x8c fp=0xc000107c90 sp=0xc000107c08 pc=0xfe374c

github.com/pulumi/pulumi/pkg/v2/resource/provider.Main.func1(0xc000378000, 0x2, 0x2)

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.16.3-0.20210105101340-061950dbc277/resource/provider/main.go:57 +0x32 fp=0xc000107ce8 sp=0xc000107c90 pc=0xe44d32

github.com/pulumi/pulumi/sdk/v2/go/common/util/rpcutil.Serve(0x0, 0x0, 0xc000107e38, 0x1, 0x1, 0x0, 0x0, 0xc00016fc20, 0xc000165810, 0xc000503170, ...)

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.16.3-0.20210105101340-061950dbc277/go/common/util/rpcutil/serve.go:64 +0x2c5 fp=0xc000107dd0 sp=0xc000107ce8 pc=0xe3cd45

github.com/pulumi/pulumi/pkg/v2/resource/provider.Main(0x125675c, 0xd, 0xc000607ec0, 0xc0003fa870, 0xc000607ee8)

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.16.3-0.20210105101340-061950dbc277/resource/provider/main.go:55 +0x34e fp=0xc000107e98 sp=0xc000107dd0 pc=0xe44a6e

github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.Serve(0x125675c, 0xd, 0x13cab04, 0x6, 0x1c5dea0, 0x47e8fe, 0x47e8fe, 0x1adff20, 0x17df7f, 0x17df7f)

        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/serve.go:14 +0xfd fp=0xc000107f28 sp=0xc000107e98 pc=0xfe311d

main.main()

        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/cmd/pulumi-resource-azure-nextgen/main.go:13 +0x9d fp=0xc000107f88 sp=0xc000107f28 pc=0xfe383d

runtime.main()

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/proc.go:204 +0x209 fp=0xc000107fe0 sp=0xc000107f88 pc=0x4385a9

runtime.goexit()

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000107fe8 sp=0xc000107fe0 pc=0x46a6c1

goroutine 18 [chan receive]:

github.com/golang/glog.(*loggingT).flushDaemon(0x20faf40)

        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b

created by github.com/golang/glog.init.0

        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x274

goroutine 6 [IO wait]:

internal/poll.runtime_pollWait(0x7f0f8a3cadd0, 0x72, 0x13ec220)

        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/netpoll.go:222 +0x55

internal/poll.(*pollDesc).wait(0xc0005ac118, 0x72, 0x13ec200, 0x1a5e5d0, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45

internal/poll.(*pollDesc).waitRead(...)

        /opt/hostedtoolcache/go/1.15.6/x64/src/internal/poll/fd_poll_runtime.go:92

internal/poll.(*FD).Read(0xc0005ac100, 0xc000690000, 0x8000, 0x8000, 0x0, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/internal/poll/fd_unix.go:159 +0x1a5

net.(*netFD).Read(0xc0005ac100, 0xc000690000, 0x8000, 0x8000, 0xd827fe, 0x10401, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/net/fd_posix.go:55 +0x4f

net.(*conn).Read(0xc0000b6040, 0xc000690000, 0x8000, 0x8000, 0x0, 0x0, 0x0)

        /opt/hostedtoolcache/go/1.15.6/x64/src/net/net.go:182 +0x8e

bufio.(*Reader).Read(0xc000078300, 0xc0005b0038, 0x9, 0x9, 0x9, 0xc00005c800, 0xc0000ba300)

        /opt/hostedtoolcache/go/1.15.6/x64/src/bufio/bufio.go:227 +0x222

io.ReadAtLeast(0x13e7d40, 0xc000078300, 0xc0005b0038, 0x9, 0x9, 0x9, 0xd7a570, 0xc000502150, 0x13c76c4)

        /opt/hostedtoolcache/go/1.15.6/x64/src/io/io.go:314 +0x87

io.ReadFull(...)

        /opt/hostedtoolcache/go/1.15.6/x64/src/io/io.go:333

golang.org/x/net/http2.readFrameHeader(0xc0005b0038, 0x9, 0x9, 0x13e7d40, 0xc000078300, 0x0, 0x0, 0xc000502150, 0x0)

        /home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:237 +0x89

golang.org/x/net/http2.(*Framer).ReadFrame(0xc0005b0000, 0xc000502150, 0xc000502100, 0x0, 0x0)

        /home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:492 +0xa5

google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0004f8700)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_client.go:1273 +0x179

created by google.golang.org/grpc/internal/transport.newHTTP2Client

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_client.go:300 +0xd31

goroutine 23 [select]:

google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0004e9200)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/balancer_conn_wrappers.go:69 +0xc8

created by google.golang.org/grpc.newCCBalancerWrapper

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/balancer_conn_wrappers.go:60 +0x172

goroutine 24 [chan receive]:

google.golang.org/grpc.(*addrConn).resetTransport(0xc0000e5080)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/clientconn.go:1156 +0x709

created by google.golang.org/grpc.(*addrConn).connect

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/clientconn.go:799 +0x12a

goroutine 7 [select]:

google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00007a140, 0x1, 0x0, 0x0, 0x0, 0x0)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/controlbuf.go:395 +0x125

google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000273ec0, 0x0, 0x0)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/controlbuf.go:513 +0x1d3

google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0004f8700)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_client.go:346 +0x7b

created by google.golang.org/grpc/internal/transport.newHTTP2Client

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_client.go:344 +0xefc
```

**Comment by mikhailshilkov** [comment]
I can see that we spin up a new instance (process) of the provider for each imported resource, which doesn't sound necessary. I'll follow up on why that happens.

**Comment by mikhailshilkov** [comment]
This is a CLI-level issue, I created https://github.com/pulumi/pulumi/issues/6119 - let's track there
