### ISSUE TITLE
Can circular dependencies be handled somehow?

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#216]
I need to create an AppInsights Component resource and a WebApp resource. The WebApp want the instrumentation key as an app setting from the output of the AppInsights Component resource and the AppInsights Component resource want to add a tag to the Tags properties with a link to the WebApp resource, i.e. a string using the Name as output from the AppInsights Component.

They both depend on each other, how can that be accomplished?

Both states are imported fine, but now I need to make the code match.

**Comment by mikhailshilkov** [comment]
You should be able to build the link to the WebApp before the app is created. It's just a string with a name, right?

**Comment by WillooWisp** [comment]
Yes, but if I don't have a dependency through an output of the name of the Component being "linked" it fails, since it seems somewhere to validate that the linked resources actually exists.

**Comment by mikhailshilkov** [comment]
Ah, so the Component creation will fail on the Azure unless the App Service already exists?

**Comment by WillooWisp** [comment]
I get this error, if I simply use a string as webAppName on on the hidden link tag on app insights Component, without a dependency to the web app. And I at the same time need the insights key as output from app insights to the web app app settings.

```
Tags =
{
    { $"hidden-link:/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/sites/<webAppName>", "Resource" }
}

```
```
panic: fatal: An assertion has failed

goroutine 31 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v2/backend/display.translateDetailedDiff(0x1cbd6a4, 0x6, 0xc000638620, 0x67, 0xc0016dede0, 0x27, 0xc0009e79e0, 0xc0009e7a70, 0xc0009e7b00, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/detailedDiff.go:145 +0x237
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiff(0x1fd16c0, 0xc000d58a20, 0x1cbd6a4, 0x6, 0xc000638620, 0x67, 0xc0016dede0, 0x27, 0xc0009e79e0, 0xc0009e7a70, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:322 +0x145
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiffResourcePreEvent(0x1cbd6a4, 0x6, 0xc000638620, 0x67, 0xc0016dede0, 0x27, 0xc0009e79e0, 0xc0009e7a70, 0xc0009e7b00, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:351 +0x298
github.com/pulumi/pulumi/pkg/v2/backend/display.RenderDiffEvent(0x1cbf1ba, 0x7, 0x1cc772f, 0xc, 0x1b169a0, 0xc000b690e0, 0xc0009edc18, 0x1cbc10e, 0x6, 0x100010000000000, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:122 +0x718
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowDiffEvents(0xc0015da420, 0x11, 0x1cbf1ba, 0x7, 0xc00117b3e0, 0xc00117b440, 0x1cbc10e, 0x6, 0x100010000000000, 0x1, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:85 +0x499
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowEvents(0xc0015da420, 0x11, 0x1cbf1ba, 0x7, 0x7ffda20aed3f, 0xc, 0xc001488858, 0x8, 0xc00117b3e0, 0xc00117b440, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/display.go:53 +0x178
created by github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).apply
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:487 +0x308
```

**Comment by mikhailshilkov** [comment]
This error doesn't look healthy... This is our engine not happy with the value. Could you create a minimal repro code and file an issue in pulumi/pulumi about this panic?

**Comment by WillooWisp** [comment]
Yes, I got it with another tag as well now, same problem.

Just add this to WebAppArgs for a WebApp, where the appServicePlanName is a simple string.

```
Tags = new InputMap<string>
{
    { $"hidden-related:/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/serverfarms/<appServicePlanName>", "empty" }
}
```

Error during preview when web app resource and app service plan resource have been imported already.

```
panic: fatal: An assertion has failed

goroutine 25 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v2/backend/display.translateDetailedDiff(0x1cbd6a4, 0x6, 0xc0012ac720, 0x5c, 0xc0019d7680, 0x22, 0xc001554a20, 0xc001554ab0, 0xc001554b40, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/detailedDiff.go:145 +0x237
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiff(0x1fd16c0, 0xc001509620, 0x1cbd6a4, 0x6, 0xc0012ac720, 0x5c, 0xc0019d7680, 0x22, 0xc001554a20, 0xc001554ab0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:322 +0x145
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiffResourcePreEvent(0x1cbd6a4, 0x6, 0xc0012ac720, 0x5c, 0xc0019d7680, 0x22, 0xc001554a20, 0xc001554ab0, 0xc001554b40, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:351 +0x298
github.com/pulumi/pulumi/pkg/v2/backend/display.RenderDiffEvent(0x1cbf1ba, 0x7, 0x1cc772f, 0xc, 0x1b169a0, 0xc0012e4640, 0xc0018bbc18, 0x1cbc10e, 0x6, 0x100010000000000, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:122 +0x718
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowDiffEvents(0xc0014ca480, 0x11, 0x1cbf1ba, 0x7, 0xc00007eb40, 0xc00007ec00, 0x1cbc10e, 0x6, 0x100010000000000, 0x1, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:85 +0x499
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowEvents(0xc0014ca480, 0x11, 0x1cbf1ba, 0x7, 0x7ffd794fcd3f, 0xc, 0xc000cc8e88, 0x8, 0xc00007eb40, 0xc00007ec00, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/display.go:53 +0x178
created by github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).apply
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:487 +0x308
```

**Comment by WillooWisp** [comment]
Reported as https://github.com/pulumi/pulumi/issues/6135

**Comment by mikhailshilkov** [comment]
Thank you. To help with your original question, a fix to https://github.com/pulumi/pulumi-azure-nextgen/issues/34 will bring a separate resource to set Web App settings. Hopefully, coming later this week.

I'll close this issue for now and let's track in those mentioned above.
