### ISSUE TITLE
Panic while checking CompositeIndexes in SqlResourceSqlContainer

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#28]
```cs
var sqlContainer = new SqlResourceSqlContainer("container1", new SqlResourceSqlContainerArgs
{
    // other props
    CompositeIndexes =
    {
        new[]
        {
            new CompositePathArgs { Path = "myOrderByPath1", Order = "Ascending" },
            new CompositePathArgs { Path = "myOrderByPath2", Order = "Descending" }
        }.ToImmutableArray()
    }
});
```

[Full code](https://gist.github.com/markjbrown/08d165dc15870bce0c4c92362ada3424)

fails with 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0xda8ac0]
goroutine 56 [running]:
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc008986a20, 0x2e, 0x0, 0xe9d120, 0xc002741aa0, 0x2e, 0x0, 0x6400000001)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:324 +0x14b0
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc0089869f0, 0x2b, 0xc00537f740, 0xe37700, 0xc007b8c0c0, 0x2b, 0xc0053592c0, 0x10)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:343 +0x280
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc008986990, 0x28, 0xc00275e708, 0xe37700, 0xc007b8c0e0, 0x28, 0x0, 0x0)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:343 +0x280
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateType(0xc00654c4b0, 0xc006e47e60, 0x17, 0xc00275ea20, 0xc002741a70, 0x50163a, 0xc007c54680, 0xc005359632)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:305 +0x3a0
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc006e47e60, 0x17, 0xc00275ed98, 0xe9d120, 0xc002741a70, 0x17, 0x0, 0x0)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:332 +0x15a6
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateType(0xc00654c4b0, 0xc007ad2ff0, 0x8, 0xc00275f0b0, 0xc002741a40, 0x0, 0x0, 0x0)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:305 +0x3a0
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc007ad2ff0, 0x8, 0xc00275f428, 0xe9d120, 0xc002741a40, 0x0, 0x0, 0x0)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:332 +0x15a6
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateType(0xc00654c4b0, 0x0, 0x0, 0xc007ac5c80, 0xc0027419b0, 0x0, 0x0, 0x0)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:305 +0x3a0
github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).Check(0xc00654c4b0, 0x11948c0, 0xc002741170, 0xc00274a2c0, 0xc00654c4b0, 0xea4601, 0xc00274b080)
/home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:246 +0x9ef
github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler.func1(0x11948c0, 0xc002741170, 0xf70420, 0xc00274a2c0, 0xf88740, 0x1e0cf00, 0x11948c0, 0xc002741170)
/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.10.2-0.20200920185652-988ebd8b8e6f/proto/go/provider.pb.go:2181 +0x8d
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x11948c0, 0xc002740c30, 0xf70420, 0xc00274a2c0, 0xc007cbefe0, 0xc007cbf000, 0x0, 0x0, 0x117af00, 0xc000336790)
/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f2
github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler(0xfba380, 0xc00654c4b0, 0x11948c0, 0xc002740c30, 0xc00664d320, 0xc000262420, 0x11948c0, 0xc002740c30, 0xc0002f5000, 0x3d7)
/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.10.2-0.20200920185652-988ebd8b8e6f/proto/go/provider.pb.go:2183 +0x152
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00010e000, 0x119eb60, 0xc000594180, 0xc0000f2900, 0xc00b5d65a0, 0x1dcfbf8, 0x0, 0x0, 0x0)
/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x511
google.golang.org/grpc.(*Server).handleStream(0xc00010e000, 0x119eb60, 0xc000594180, 0xc0000f2900, 0x0)
/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcd4
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0007168b0, 0xc00010e000, 0x119eb60, 0xc000594180, 0xc0000f2900)
/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa8

azure-nextgen:documentdb:SqlResourceSqlContainer (container1):
error: transport is closing
```

**Comment by mikhailshilkov** [comment]
@markjbrown Could you give a try to the NuGet version `0.1.1-alpha.1601308828`?

**Comment by markjbrown** [comment]
ok, composite indexes are now working. Thanks Mikhail!
