### ISSUE TITLE
InvalidOperationException when using the Synapse.Workspace resource

### ISSUE THREAD

**Issue by JamesDawson** [pulumi/pulumi-azure-nextgen#32]
Whilst doing some initial evaluation using this stack definition:

```
var resourceGroup = new ResourceGroup("resourceGroup", new ResourceGroupArgs
{
    ResourceGroupName = resourceGroupName,
    Location = resourceGroupLocation
});

var storageAccount = new StorageAccount("storageAccount", new StorageAccountArgs
{
    ResourceGroupName = resourceGroup.Name,
    AccountName = storageAccountName,
    Location = resourceGroupLocation,
    Sku = new SkuArgs
    {
        Name = "Standard_LRS",
        Tier = "Standard"
    },
    Kind = "StorageV2",
    IsHnsEnabled = true
});

var blobContainer = new BlobContainer("blobContainer", new BlobContainerArgs
{
    AccountName = storageAccount.Name,
    ContainerName = "default",
    ResourceGroupName = resourceGroup.Name,
});

var synapseWs = new Synapse.Workspace("synapseWs", new Synapse.WorkspaceArgs
{
    DefaultDataLakeStorage = new Synapse.Inputs.DataLakeStorageAccountDetailsArgs
    {
        AccountUrl = storageAccount.PrimaryEndpoints.Apply(p => p.Dfs),
        Filesystem = "data",
    },
    Identity = new Synapse.Inputs.ManagedIdentityArgs
    {
        Type = "SystemAssigned",
    },
    Location = resourceGroupLocation,
    ResourceGroupName = resourceGroup.Name,
    SqlAdministratorLogin = sqlAdminUsername,
    SqlAdministratorLoginPassword = sqlAdminPassword,
    WorkspaceName = synapseWorkspaceName,
});
```

We get the following exception:

```
System.InvalidOperationException: Expected System.Collections.Immutable.ImmutableDictionary`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] but got System.String deserializing Pulumi.AzureNextGen.Synapse.V20190601Preview.Workspace.extraProperties
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

The resources are being created and appear in the portal.

**Comment by mikhailshilkov** [comment]
This issue is fixed in the next dev build and will be released in 0.2.0 this week
