### ISSUE TITLE
ListNamespaceKeys returns 404 ParentResourceNotFound

### ISSUE THREAD

**Issue by william-liebenberg** [pulumi/pulumi-azure-nextgen#35]
Hi all

In my stack im provisioning a bunch of things and among them are EventHubs and Stream Analytics. I also need to create some EventHub Input and Output sources (`EventHubStreamInputDataSourceArgs` and `EventHubOutputDataSourceArgs`) to hook into an Azure Stream Analytics instance. One of the required inputs for an EventHub input stream is the `SharedAccessPolicyKey`. 

I simply just want to grab the `RootManageSharedAccessKey` (don't yell) that is created with the EventHub namespace, but whatever I have tried so far always returns a 404 ParentResourceNotFound error during the `pulumi up` validation/preview stage.

Here is the code I try to grab the `SharedAccessPolicyKey`:

```csharp
using ASA2017 = Pulumi.AzureNextGen.StreamAnalytics.V20170401Preview;
...
public static void SetupAnalyticsSources()
{
	var eventHubStreamInputDataSource = new ASA2017.Inputs.EventHubStreamInputDataSourceArgs()
	{
		ConsumerGroupName = consumerGroupName,
		EventHubName = hubName,
		ServiceBusNamespace = namespaceName,
		SharedAccessPolicyKey = Output.Tuple<string, string, string>(resourceGroupName, namespaceName, namespaceAuthorizationRuleName)
                                        .Apply(inputs => Output.Create(GetEventHubNamespaceAuthorizationRuleKey(inputs.Item1, inputs.Item2, inputs.Item3))),
		SharedAccessPolicyName = namespaceAuthorizationRuleName,
		Type = "Microsoft.ServiceBus/EventHub",
	};

        // ... create more stuff :)
}

private static async Task<string> GetEventHubNamespaceAuthorizationRuleKey(string resourceGroupName, string namespaceName, string authorizationRuleName)
{
	var namespaceKeys = await ListNamespaceKeys.InvokeAsync(new ListNamespaceKeysArgs
	{
		ResourceGroupName = resourceGroupName,
		AuthorizationRuleName = authorizationRuleName,
		NamespaceName = namespaceName
	});
	return namespaceKeys.PrimaryKey;
}
```

The error I get from `pulumi up` is:

```
error: Running program 'C:\Users\awlie\source\repos\HTHBeacon\Beacon\build\infrastructure\bin\Debug\netcoreapp3.1\Beacon.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="invocation of azure-nextgen:eventhub/latest:listNamespaceKeys returned an error: request failed /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/beacon-demo/providers/Microsoft.EventHub/namespaces/beacon-bus-demo/authorizationRules/RootManageSharedAccessKey/listKeys: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'beacon-bus-demo' not found."")
       at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
       at Pulumi.Deployment.InvokeAsync[T](String token, InvokeArgs args, InvokeOptions options, Boolean convertResult)
       at MyStack.GetEventHubNamespaceAuthorizationRuleKey(String resourceGroupName, String namespaceName, String authorizationRuleName) in C:\Users\awlie\source\repos\HTHBeacon\Beacon\build\infrastructure\MyStack.cs:line 1397
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
```

I've checked all the obvious things like correct resourcegroup names, eventhub/namespace names, etc.

Any ideas on what I should be doing to get this working?

**Comment by mikhailshilkov** [comment]
Hey @william-liebenberg :)

This likely happens because `GetEventHubNamespaceAuthorizationRuleKey` is executed before the resources are actually created. It executes as soon as it can because it has no dependency defined on the resources.

To fix this, you need to pass an actual output from your event hub to `Output.Tuple`. For example:

```cs
var resourceGroup = new ResourceGroup(...);
var eventHubNamespace = new Namespace(...);
var sharedAccessPolicyKey = Output.Tuple<string, string, string>(resourceGroup.Name, namespace.Name, namespaceAuthorizationRuleName)
    .Apply(inputs => Output.Create(GetEventHubNamespaceAuthorizationRuleKey(inputs.Item1, inputs.Item2, inputs.Item3))),
```

Note `resourceGroup.Name, namespace.Name` there - they are output properties of type `Output<string>`, not plain strings. Using outputs would defer the execution of the invoke until the resource creation is completed.

**Comment by william-liebenberg** [comment]
Thanks @mikhailshilkov 

It all works now -- was easy to test on my small repro but took a while on my prod script. 

Super happy!!!!
