### ISSUE TITLE
Error retrieving keys with Azure NextGen provider prior to creation of storage account with Azure provider

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/pulumi-azure-nextgen#98]
In the situation where:
- a storage account is to be created using the Azure provider, and
- the primary storage key is to be retrieved using the Azure NextGen provider,

the following C# code works once the storage account has been created but errors out beforehand:
```
...     // Export the primary key of the Storage Account
        this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2)));
    }

    [Output]
    public Output<string> PrimaryStorageKey { get; set; }

    private static async Task<string> GetStorageAccountPrimaryKey(string resourceGroupName, string accountName)
    {
        var accountKeys = await Storage.ListStorageAccountKeys.InvokeAsync(new Storage.ListStorageAccountKeysArgs
        {
            ResourceGroupName = resourceGroupName,
            AccountName = accountName
        });
        return accountKeys.Keys[0].Value;
    }
}
```
with the following (using azure-nextgen 0.2.4):
```
error: Running program 'C:\example\bin\Debug\netcoreapp3.1\example.dll' failed with an unhandled exception:
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="invocation of azure-nextgen:storage/latest:listStorageAccountKeys returned an error: request failed /subscriptions/subscription/resourceGroups/examplerg/providers/Microsoft.Storage/storageAccounts/examplesa/listKeys: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Storage/storageAccounts/examplesa' under resource group 'examplerg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"")
   at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
   at Pulumi.Deployment.InvokeAsync[T](String token, InvokeArgs args, InvokeOptions options, Boolean convertResult)
   at EgDataStorage.GetStorageAccountPrimaryKey(String resourceGroupName, String accountName) in C:\example\EgDataStorage.cs:line 301
   at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
   at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
   at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
   at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
   at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
   at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
   at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Pulumi.Deployment.Runner.WhileRunningAsync()
```
This does not occur in situations where the storage account is to be created with the Azure NextGen provider. Although the above code could be changed to use the Azure provider to retrieve the keys, this doesn't seem to be necessary because after the storage account is created using the Azure provider, the Azure Nextgen provider is then used to successfully create BlobContainers and Queues.

**Comment by mikhailshilkov** [comment]
What prevents you from getting the storage account key from the old provider's resource?

To make your code work you'd likely need to add another property to `Tuple` that is only resolved once the resource is created:

```cs
this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name, egStorageAccount.Id).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2)));
```

**Comment by jamesianberry** [comment]
Actually the same error is found when trying to get the storage account key using the azure provider (3.29.0):
```
...     // Export the primary key of the Storage Account
        this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2)));
    }

    [Output]
    public Output<string> PrimaryStorageKey { get; set; }

    private static async Task<string> GetStorageAccountPrimaryKey(string resourceGroupName, string accountName)
    {
        var accountKeys = await Azure.Storage.GetAccount.InvokeAsync(new Azure.Storage.GetAccountArgs
        {
            ResourceGroupName = resourceGroupName,
            Name = accountName
        });
        return accountKeys.PrimaryAccessKey;
    }
}
```
with the following result on preview when the storage account doesn't exist:
```
    error: Running program 'C:\example\bin\Debug\netcoreapp3.1\example.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="invocation of azure:storage/getAccount:getAccount returned an error: invoking azure:storage/getAccount:getAccount: Error: Storage Account "examplesa" (Resource Group "examplerg") was not found")
       at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
       at Pulumi.Deployment.InvokeAsync[T](String token, InvokeArgs args, InvokeOptions options, Boolean convertResult)
       at MenuDataStorage.GetStorageAccountPrimaryKey(String resourceGroupName, String accountName) in C:\example\EgStorageAccount.cs:line 307
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```
It's strange that I don't get this error with other storage accounts that are created using azure-nextgen. 
I will now try the `Tuple` with the `Id`

**Comment by jamesianberry** [comment]
And that avoids the error:
```
...     // Export the primary key of the Storage Account
        this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name, egStorageAccount.Id).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2, names.Item3)));
    }

    [Output]
    public Output<string> PrimaryStorageKey { get; set; }

    private static async Task<string> GetStorageAccountPrimaryKey(string resourceGroupName, string accountName, string accountId)
    {
        var accountKeys = await Azure.Storage.GetAccount.InvokeAsync(new Azure.Storage.GetAccountArgs
        {
            ResourceGroupName = resourceGroupName,
            Name = accountName
        });
        return accountKeys.PrimaryAccessKey;
    }
}
```
But still I don't know why storage accounts created using the azure provider need this and those using the azure-nextgen provider don't.

**Comment by mikhailshilkov** [comment]
With the old provider, it should be as simple as `egStorageAccount.PrimaryAccessKey`.

The last snippet can be simplified to

```cs
...     // Export the primary key of the Storage Account
        this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name, egStorageAccount.Id).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2)));
    }

    [Output]
    public Output<string> PrimaryStorageKey { get; set; }

    private static async Task<string> GetStorageAccountPrimaryKey(string resourceGroupName, string accountName)
    {
        var accountKeys = await Azure.Storage.GetAccount.InvokeAsync(new Azure.Storage.GetAccountArgs
        {
            ResourceGroupName = resourceGroupName,
            Name = accountName
        });
        return accountKeys.PrimaryAccessKey;
    }
}
```

**Comment by jamesianberry** [comment]
So there are three approaches that work (when using the azure provider to create the storage account):
a) a simple apply without a `tuple` using the azure provider:
```
this.PrimaryStorageKey = egStorageAccount.PrimaryAccessKey.Apply(key => Output.CreateSecret(key)); 
```
If a secret isn't required, it's even simpler:
```
this.PrimaryStorageKey = egStorageAccount.PrimaryAccessKey
```
Is it possible to create the secret without the Apply?
b) including the `Id` in the `tuple` using the azure provider:
```
...     // Export the primary key of the Storage Account
        this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name, egStorageAccount.Id).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2)));
    }

    [Output]
    public Output<string> PrimaryStorageKey { get; set; }

    private static async Task<string> GetStorageAccountPrimaryKey(string resourceGroupName, string accountName)
    {
        var accountKeys = await Azure.Storage.GetAccount.InvokeAsync(new Azure.Storage.GetAccountArgs
        {
            ResourceGroupName = resourceGroupName,
            Name = accountName
        });
        return accountKeys.PrimaryAccessKey;
    }
}
```
c) including the `Id` in the `tuple` using the azure-nextgen provider:
```
...     // Export the primary key of the Storage Account
        this.PrimaryStorageKey = Output.Tuple(resourceGroupName, egStorageAccount.Name, egStorageAccount.Id).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryKey(names.Item1, names.Item2)));
    }

    [Output]
    public Output<string> PrimaryStorageKey { get; set; }

    private static async Task<string> GetStorageAccountPrimaryKey(string resourceGroupName, string accountName)
    {
        var accountKeys = await Storage.ListStorageAccountKeys.InvokeAsync(new Storage.ListStorageAccountKeysArgs
        {
            ResourceGroupName = resourceGroupName,
            AccountName = accountName
        });
        return accountKeys.Keys[0].Value;
    }
}
```
What I don't understand is why when the azure-nextgen provider both creates the storage account and retrieves the key, the `tuple` doesn't require the `Id` but it does when the storage account is created using the azure provider.
